// Catálogo único de detalles bromatológicos
export const NUTRIENTES = [
  { code: "MS",  label: "Materia seca" },
  { code: "EE",  label: "Extracto de éter" },
  { code: "CSF", label: "Carbohidratos sin fibra" },
  { code: "FDN", label: "Fibra detergente neutra" },
  { code: "NDT", label: "Nutrientes digestibles totales" },
  { code: "EN",  label: "Energía neta" },
  { code: "EM",  label: "Energía metabolizable" },
  { code: "PDR", label: "Proteína degradable en el rumen" },
  { code: "PND", label: "Proteína no degradable en el rumen" },
  { code: "PC",  label: "Proteína cruda" },
  { code: "PM",  label: "Proteína metabolizable" },
  { code: "Ca",  label: "Calcio" },
  { code: "P",   label: "Fósforo" },
  { code: "Mg",  label: "Magnesio" },
  { code: "K",   label: "Potasio" },
  { code: "Na",  label: "Sodio" },
  { code: "S",   label: "Azufre" },
  { code: "Co",  label: "Cobalto" },
  { code: "Cu",  label: "Cobre" },
  { code: "I",   label: "Yodo" },
  { code: "Mn",  label: "Manganeso" },
  { code: "Se",  label: "Selenio" },
  { code: "Zn",  label: "Zinc" },
];
